---
- name: Ensure all required PostgreSQL dependencies ready
  hosts: postgresql-all
  sudo: yes
  sudo_user: root
  vars_files:
    - 'defaults/postgresql.yml'
  tasks:
    - include: 'tasks/postgresql.yml'

- name: Ensure the master PostgreSQL server is ready
  hosts: postgresql-master
  sudo: yes
  sudo_user: postgres
  vars_files:
    - 'defaults/postgresql.yml'
  tasks: 
    - include: 'tasks/master.yml'

- name: Ensure all standby servers are ready
  hosts: postgresql-standbys
  sudo: yes
  sudo_user: postgres
  vars_files:
    - 'defaults/postgresql.yml'
  tasks:
    - include: 'tasks/standby.yml'

