---
- name: Ensure all virtual machines are ready
  hosts: all
  sudo: yes
  sudo_user: root
  vars_files: # load default variables from YAML files below
    - 'defaults/postgresql.yml'
    - 'defaults/aws.yml'
  gather_facts: no
  tasks:
    - include: 'tasks/infrastructure.yml'

- name: Ensure the master PostgreSQL server is ready
  hosts: master
  sudo: yes
  sudo_user: root
  vars_files:
    - 'defaults/postgresql.yml'
    - 'defaults/aws.yml'
  gather_facts: no
  tasks: 
    - include: 'tasks/master.yml'

- name: Ensure all standby servers are ready
  hosts: standbys
  sudo: yes
  sudo_user: root
  vars_files:
    - 'defaults/postgresql.yml'
    - 'defaults/aws.yml'
  gather_facts: no
  tasks:
    - include: 'tasks/standby.yml'

