---
- name: Ensure all virtual machines are ready
  hosts: 127.0.0.1
  connection: local
  vars_files: # load default variables from YAML files below
    - 'defaults/postgresql.yml'
    - 'defaults/aws.yml'
  gather_facts: yes
  tasks:
    - include: 'tasks/provision.yml'

- name: Ensure all required PostgreSQL dependencies ready
  hosts: all
  sudo: yes
  sudo_user: root
  vars_files:
    - 'defaults/postgresql.yml'
    - 'defaults/aws.yml'
  gather_facts: yes
  tasks:
    - include: 'tasks/postgresql.yml'

- name: Ensure the master PostgreSQL server is ready
  hosts: master
  sudo: yes
  sudo_user: postgres
  vars_files:
    - 'defaults/postgresql.yml'
    - 'defaults/aws.yml'
  gather_facts: yes
  tasks: 
    - include: 'tasks/master.yml'

- name: Ensure all standby servers are ready
  hosts: standbys
  sudo: yes
  sudo_user: postgres
  vars_files:
    - 'defaults/postgresql.yml'
    - 'defaults/aws.yml'
  gather_facts: yes
  tasks:
    - include: 'tasks/standby.yml'

