---
- hosts: all
  sudo: yes
  sudo_user: root
  vars_files: # load default variables from YAML files below
    - 'defaults/postgresql.yml'
    - 'defaults/aws.yml'
  gather_facts: no
  tasks:

- hosts: master
  sudo: yes
  sudo_user: root
  vars_files:
    - 'defaults/postgresql.yml'
    - 'defaults/aws.yml'
  gather_facts: no
  tasks: 

- hosts: standbys
  sudo: yes
  sudo_user: root
  vars_files:
    - 'defaults/postgresql.yml'
    - 'defaults/aws.yml'
  gather_facts: no
  tasks:

