- name: Ensure PostgreSQL users are present
  postgresql_user:
    state: present
    name: {{ item.name }}
    password: {{ item.password }}
    role_attr_flags: {{ item.roles }}
  with_items: postgresql_users

- name: Ensure replication role is present
  postgresql_user:
    state: present
    name: {{ postgresql_replication_user.name }}
    password: {{ postgresql_replication_user.password }}
    role_attr_flags: {{ postgresql_replication_user.roles }}

# TODO: Ensure streaming replication configuration is ready

# TODO: Ensure the database is present

- name: Ensure PostgreSQL extensions are present
  postgresql_ext:
    state: present
    name: {{ item }}
    db: {{ bişi }}
  with_items: postgresql_extensions

# TODO: Ensure roles are associated with the database

# TODO: Ensure the database dump file is imported

