
- name: Ensure PostgreSQL users are present
  postgresql_user:
    state: present
    name: {{ item.name }}
    password: {{ item.password }}
    role_attr_flags: {{ item.roles }}
  with_items: postgresql_users

- name: Ensure replication role is present
  postgresql_user:
    state: present
    name: {{ postgresql_replication_user.name }}
    password: {{ postgresql_replication_user.password }}
    role_attr_flags: {{ postgresql_replication_user.roles }}

- name: Ensure streaming replication configuration is ready
  template:
    src: pg_hba.conf.j2
    dest: '/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf'
    owner: postgres
    group: postgres
    mode: 0640

- name: Ensure the database is present
  postgresql_db:
    state: present
    name: {{ postgresql_database_name }}

- name: Ensure PostgreSQL extensions are present
  postgresql_ext:
    state: present
    name: {{ item }}
    db: {{ bişi }}
  with_items: postgresql_extensions

- name: Ensure roles are associated with the database
  postgresql_privs:
    state: present
    db: {{ postgresql_database_name }}
    privs: ALL
    type: schema
    objs: public
    role: {{ item.name }}
  with_items: postgresql_users

# TODO: Ensure the database dump file is imported

