#
# Manage the PostgreSQL data folder
#
- name: Ensure the data folder for current version is present
  file: path="/var/lib/postgresql/{{ postgresql_version }}" state=directory mode=0777


#
# Configure the system for PostgreSQL packages
#

- name: Ensure the PostgreSQL Global Development Group APT repository is enabled
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/dists {{ ec2_os_version }}-pgdg main" state=present

- name: Ensure the repository signing key is present
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Update the package list # apt-get update
  apt: update_cache=yes

#
# Manage PostgreSQL packages
#

- name: Ensure PostgreSQL is present
  apt: name="postgresql-{{ postgresql_version }}" state=latest

- name: Ensure the psycopg2 package is present (this will be required for Ansible PostgreSQL modules)
  apt: name=python-psycopg2 state=latest

- name: Ensure PostgreSQL contrib package is present, if requested
  apt: name="postgresql-contrib-{{ postgresql_version }}" state=latest
  when: postgresql_contrib # because when expects variables 

- name: Ensure PostgreSQL configuration is as requested
  lineinfile:
    state: present
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: "{{ item.find }}"
    line: "{{ item.replace }}"
  with_items: postgresql_conf_statements
  register: postgresql_conf

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started  

- name: Ensure the data folder has right ownership
  file: path="/var/lib/postgresql" state=directory owner=postgres group=postgres

- name: Ensure the data folder for current version has right ownership
  file: path="/var/lib/postgresql/{{ postgresql_version }}" state=directory owner=postgres group=postgres

